on:
  repository_dispatch:
    types: [update]
  workflow_dispatch:
    inputs:
      version:
        description: 'New version. ex: 1.0.0'
        required: true
      sha256:
        description: 'SHA256 of dmg file'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: Casks
      - name: Modify a Cask
        run: |
          gsed --in-place --regexp-extended 's/version "[0-9]+\.[0-9]+\.[0-9]+"/version: "${{ github.event.inputs.version }}"/' Casks/macskk.rb
          gsed --in-place --regexp-extended 's/sha256 "[0-9a-f]{64}"/sha256: "${{ github.event.inputs.sha256 }}"/' Casks/macskk.rb
      - name: Commit & Push
        run: |
          git diff --exit-code --quiet
          if [ $? -eq 1 ]; then
            git add --update
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m "Update Cask for version ${{ github.event.inputs.version }}"
            git push
          fi
