on:
  repository_dispatch:
    types: [update]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: Casks
      - name: Modify a Cask
        run: |
          sed --in-place --regexp-extended 's/version "[0-9]+\.[0-9]+\.[0-9]+"/version "${{ github.event.client_payload.version }}"/; s/sha256 "[0-9a-f]{64}"/sha256 "${{ github.event.client_payload.sha256 }}"/' Casks/macskk.rb
      - name: Commit & Push
        run: |
          if [ -n "$(git diff --name-only Casks/macskk.rb)" ]; then
            git add --update
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m "Update Cask for version ${{ github.event.client_payload.version }}"
            git push
          fi
